# Configuração do Console Appender
appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.follow = true
appender.console.layout.type = PatternLayout
#appender.console.layout.pattern = %style{%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}{America/Sao_Paulo}}{#7D55F3} %highlight{${LOG_LEVEL_PATTERN:-%5p}}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=green, DEBUG=green bold, TRACE=blue} %style{%pid}{magenta}  %style{[%X{x-correlation-id}]}{cyan} %style{%-40.40C{1.}}{#0163DA} : %m%n%throwable{3}
appender.console.layout.pattern = %style{%d{${LOG_DATEFORMAT_PATTERN:-HH:mm:ss.SSS}}{America/Sao_Paulo}}{#7D55F3} %highlight{${LOG_LEVEL_PATTERN:-%5p}}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=green, DEBUG=green bold, TRACE=blue} %style{%pid}{magenta}  %style{[%X{x-correlation-id}]}{cyan} %style{%-40.40C{1.}}{#0163DA} : %m%n%throwable{3}
appender.console.layout.disableAnsi=false

# Configuração dos Loggers
rootLogger.level = info
#rootLogger.appenderRef.rolling.ref = RollingFile
rootLogger.appenderRef.console.ref = Console